#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'

cookbook 'apt'
cookbook 'ohai'
cookbook 'vim'
cookbook 'nano'
cookbook 'build-essential', '>= 1.4.2'
cookbook 'apache2', '>= 1.8.4'
cookbook 'mysql', '>= 3.0.12'
cookbook 'database', '>= 1.3'
cookbook 'php'
cookbook 'phpunit', '>= 0.0.9'
cookbook 'composer', '>= 0.0.5'

cookbook 'wpdeploy-configure',
    :path => "custom-cookbooks/wpdeploy-configure"

cookbook 'wpdeploy-wordpress',
    :path => "custom-cookbooks/wpdeploy-wordpress"

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
